development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEVE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_STAG"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PROD"] %>
